name: Build kafka-connect-common

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache sbt
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Compile and Package kafka-connect-common
        run: sbt "project common" clean compile package

      - name: List JARs in target folder
        run: ls -lah kafka-connect-common/target/scala-2.13/

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: kafka-connect-common
          path: kafka-connect-common/target/scala-2.13/*.jar
