name: Build kafka-connect-common

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java and SBT
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.11"

    - name: Build kafka-connect-common
      run: sbt "project kafka-connect-common" clean compile package

    - name: Upload kafka-connect-common JAR
      uses: actions/upload-artifact@v4
      with:
        name: kafka-connect-common-jar
        path: kafka-connect-common/target/scala-2.12/*.jar
